import React from "react"
import Head from "next/head"

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Next Study Timer</title>
        {/* <meta name='description' content='Generated by create next app' /> */}
        {/* <link rel='icon' href='/favicon.ico' /> */}
      </Head>
      <span className='timer-title'>Next Study Timer</span>
      {children}
    </div>
  )
}

export default Layout
